website/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from register.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/mainsite/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models


class Product(models.Model):
    cat = (
        ('Electronic', 'Electronic'),
        ('Clothing', 'Clothing'),
        ('Automobiles', 'Automobiles'),
        ('Sport', 'Sport'),
        ('Books', 'Books'),
        ('Services', 'Services'),
        ('Other', 'Other'),

    )
    product_name = models.CharField(max_length=30, blank=False)
    description = models.TextField(max_length=600, blank=False)
    category = models.CharField(max_length=30, choices=cat, blank=False)
    price = models.FloatField(blank=False)
    city = models.CharField(max_length=30, blank=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_added = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.product_name} - {self.price} - listed by: {self.owner}'


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        cart = Cart.objects.get(user=self.user)
        return f'{self.user.username}\'s shopping cart with {cart.products.all().count()} items'


class Order(models.Model):
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    email = models.EmailField(blank=False)
    telephone = models.CharField(max_length=13, blank=False, default='+359')
    address = models.CharField(max_length=50, blank=False)
    user = models.ForeignKey(User, null=False, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    total_cost = models.IntegerField(default=0)
    total_products = models.IntegerField(default=0)


    def __str__(self):
        return f'Order id {self.id}, made by {self.user.username} on {self.date}'


class ProfilePicture(models.Model):
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class ProductPicture(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='product_pictures/',blank=False,verbose_name='Image')

website/mainsite/views/cart_view.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from mainsite.models import Cart, Product
from mainsite.views.categoryfn import category_fn


def add_to_cart(request, pk):
    user = User.objects.get(pk=pk)
    my_cart = Cart.objects.get_or_create(user=user)[0]
    categories = category_fn()
    if request.method == 'POST':
        product_id = request.POST['add']
        product = Product.objects.get(pk=product_id)
        my_cart.products.add(product)
        return redirect('index')

    else:
        products = my_cart.products.all()
        total = sum(products.values_list('price', flat=True))
        context= {
            'products': products,
            'cart_pk': pk,
            'total': total,
            'len': len(products),
            'categories': categories
        }
        return render(request, 'cart.html', context)


def remove_from_cart(request, pk):
    categories = category_fn()

    if request.method == 'GET':
        cart_pk = int(request.GET['delete'])
        cart = Cart.objects.get(user_id=cart_pk)
        product = Product.objects.get(pk=pk)
        cart.products.remove(product)
        products = cart.products.all()
        total = sum(products.values_list('price', flat=True))

        context = {
            'products': products,
            'cart_pk': cart_pk,
            'categories': categories,
            'total': total,

        }
        return render(request, 'cart.html', context)

website/mainsite/views/categories_view.py
from django.shortcuts import render

from mainsite.forms import SortForm
from mainsite.models import Product
from mainsite.views.categoryfn import category_fn
from django.core.paginator import Paginator


def extract_filter_value(params):
    order = params['order'] if 'order' in params else '-date_added'
    return order


def category_view(request, category):
    category = category
    categories = category_fn()
    if request.method == 'GET':
        #products = Product.objects.filter(category=category)

        sort_form = SortForm()
        order = extract_filter_value(request.GET)

        products = Product.objects.filter(category=category).order_by(order)

        paginator = Paginator(products, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


        context = {
            'category': category,
            'products': products,
            'categories': categories,
            'len': len(products),
            'page_obj': page_obj,
            'sort_form': sort_form,
            'order': order,
        }
        return render(request, 'category.html', context)


def search_in_category(request, category):
    category = category
    categories = category_fn()

    query = request.GET['q']
    sort_form = SortForm()
    order = extract_filter_value(request.GET)
    products = Product.objects.filter(category=category).filter(product_name__icontains=query).order_by(order)

    paginator = Paginator(products, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'category': category,
        'products': products,
        'categories': categories,
        'len': len(products),
        'page_obj': page_obj,
        'query': query,
        'sort_form': SortForm(),
        'order': order,
    }
    return render(request, 'category.html', context)

website/mainsite/views/checkout.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from mainsite.forms import OrderForm
from mainsite.models import Cart
from mainsite.views.categoryfn import category_fn


def checkout(request):
    if request.method == 'GET':
        form = OrderForm()
        form.fields['email'].initial = User.objects.get(pk=request.user.id).email
        categories = category_fn()
        context = {
            'form': form,
            'categories': categories,
        }
        return render(request, 'checkout.html', context)


def order(request, pk):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        user = User.objects.get(pk=pk)
        cart = Cart.objects.get(user=user)
        products = cart.products.all()

        context = {
            'products': products,
            'len': len(products),
        }
        if form.is_valid():
            new = form.save(commit=False) # Setting foreign key
            new.user = user
            new.save()
            cart.products.clear()
            return render(request, 'order_complete.html', context)
        context = {
            'form': form,
        }
        return render(request, 'checkout.html', context)

website/mainsite/views/checkout_view.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from mainsite.forms import OrderForm
from mainsite.models import Cart
from mainsite.views.categoryfn import category_fn


def checkout(request):
    if request.method == 'GET':
        form = OrderForm()
        form.fields['email'].initial = User.objects.get(pk=request.user.id).email
        categories = category_fn()
        context = {
            'form': form,
            'categories': categories,
        }
        return render(request, 'checkout.html', context)


def order(request, pk):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        user = User.objects.get(pk=pk)
        cart = Cart.objects.get(user=user)
        products = cart.products.all()
        cost = sum(products.values_list('price', flat=True))
        print(cost)
        context = {
            'products': products,
            'len': len(products),
            'cost': cost,
        }
        if form.is_valid():
            new = form.save(commit=False) # Setting foreign key
            new.user = user
            new.total_cost = cost
            new.total_products = len(products)
            new.save()
            cart.products.clear()
            return render(request, 'order_complete.html', context)
        context = {
            'form': form,
        }
        return render(request, 'checkout.html', context)

website/mainsite/views/create_product_view.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.shortcuts import render, redirect

from mainsite.forms import ProductForm, ProductPictureForm
from mainsite.models import ProductPicture
from mainsite.views.categoryfn import category_fn


@login_required(login_url='login')
def create_product(request):
    ImageFormSet = modelformset_factory(ProductPicture, form=ProductPictureForm, extra=4)

    categories = category_fn()
    if request.method == 'GET':
        form = ProductForm()
        formset = ImageFormSet(queryset=ProductPicture.objects.none())
        context = {
            'form': form,
            'formset': formset,
            'categories': categories,
        }
        return render(request, 'create_product.html', context)
    else:
        user = request.user
        form = ProductForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES, queryset=ProductPicture.objects.none())

        if form.is_valid() and formset.is_valid():
            product = form.save(commit=False) # Setting foreign key
            product.owner = user
            product.save()

            for f in formset.cleaned_data:
                if f:
                    image = f['image']
                    photo = ProductPicture(product=product, images=image)
                    photo.save()
            return redirect('index')

        form = ProductForm()
        context = {
            'form': form,
            'formset': formset,
            'categories':categories,
        }
        return render(request, 'create_product.html', context)

website/mainsite/views/profile_view.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import UpdateView

from mainsite.models import ProfilePicture
from mainsite.views.categoryfn import category_fn


def profile(request, slug):
    if request.method == 'GET':
        owner = User.objects.get(username=slug)
        try:
            profile_picture_exists = owner.profilepicture
        except ProfilePicture.DoesNotExist:
            profile_picture_exists = ProfilePicture(profile_picture='profile_pics/default_profile_picture.png', user=owner)
        products = owner.product_set.all()
        categories = category_fn()
        context = {
            'products': products,
            'owner': owner,
            'categories': categories,
            'profile_picture_exists': profile_picture_exists,
        }
        return render(request, 'profile.html', context)


class ProfileUpdate(UpdateView):
    model = User
    fields = ('username','email', 'first_name', 'last_name')
    template_name = 'update_profile.html'

website/mainsite/views/search.py
from django.shortcuts import render
from mainsite.models import Product
from mainsite.views.categoryfn import category_fn


def search(request):
    query = request.GET['q']
    products = Product.objects.all()
    categories = category_fn()
    matched = []
    for product in products:
        if query.lower() in product.product_name.lower() or query.lower() in product.description.lower():
            matched.append(product)
    context={
        'query': query,
        'matched': matched,
        'categories': categories,
    }
    return render(request, 'search.html', context)

website/mainsite/views/search_view.py
from django.shortcuts import render
from django.views.generic import ListView

from mainsite.models import Product
from mainsite.views.categoryfn import category_fn


# def search(request):
#     query = request.GET['q']
#     products = Product.objects.filter(
#         product_name__icontains=query) | Product.objects.filter(description__icontains=query)
#     categories = category_fn()
#
#     context = {
#         'query': query,
#         'matched': products,
#         'categories': categories,
#     }
#     return render(request, 'search.html', context)

class SearchView(ListView):
    template_name = 'search.html'
    model = Product
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q')
        context = super().get_context_data(**kwargs)
        categories = category_fn()
        context['query'] = query
        context['categories'] = categories

        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = None
        if query:
            object_list = Product.objects.filter(
                product_name__icontains=query) | Product.objects.filter(description__icontains=query)

        return object_list

website/templates/admin_page.html
{% extends 'shared/base.html' %}
{% load static %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/admin_page.css' %}">
{% endblock %}
{% block content %}
    <div class="parent">
        <div class="item">
        <h3 style="text-align: center;">{{ users.count }} registered users</h3>
        <hr style="border: 1px solid black">
        {% for user in users %}
            <p class="users">{{ user.username }}</p>
        {% endfor %}
        </div>
        <div class="item">
          <h3>Total products: {{ products.count }}</h3>
          <hr>
          {% for product in products %}
          <p>{{ product.product_name }} - {{ product.price }}lv</p>
          {% endfor %}
        </div>
        <div class="item">
        <h3>{{ orders.count }} completed orders</h3>
        <hr>
        {% for order in orders %}
        <p>id: {{ order.id }} | Made by: {{ order.user.username }} - Cost: {{ order.total_cost }} - {{ order.total_products }} items</p>
        {% endfor %}
</div>
    </div>
{% endblock %}

website/templates/cart.html
{% extends 'shared/base.html' %}
{% load static %}

{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}

{% block content %}
    {% if user.pk == cart_pk %}
        {% if len == 0 %}
            <h1 class="display-1 empty-cart">Your cart is empty</h1>
        {% else %}
            <div class="total">
                <div class="total-head">
                    <h1>Your total is: {{ total }}lv.</h1>

                    <form method="get" action="{% url 'checkout' %}">
                        <button type="submit" class="btn btn-warning">Continue to checkout</button>
                    </form>
                </div>
            </div>

            <div class="cart-container">
                {% for product in products %}

                    <div class="card" style="width: 80%; margin-bottom: 1.2rem">
                        <a href="{% url 'product' product.id product.product_name %} ">
                            {% with product.productpicture_set.all|first as image %}
                                <img src="{{ image.images.url }}"
                                     class="card-img-top" alt="{{ product.product_name }}"
                                     style="max-width: 100%; max-height: 80%;">
                            {% endwith %}
                        </a>
                        <div class="card-body">
                            <a href="{% url 'product' product.id product.product_name %} ">

                                <h5 class="card-title">{{ product.product_name }}</h5>
                            </a>
                            <h6 class="card-title">{{ product.price }}lv</h6>
                            <p class="card-text">{{ product.description }}.</p>
                            <form method="get" action="{% url 'remove_from_cart' product.pk %}">
                                {% csrf_token %}
                                <div>
                                    <button class="btn btn-danger" type="submit" name="delete" value="{{ cart_pk }}">
                                        Delete from cart
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% else %}


        <h1 class="denied">Access denied</h1>
    {% endif %}

{% endblock %}

website/templates/category.html
{% extends 'shared/base.html' %}
{% load static %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}
{% block content %}
    {% if products %}
        {% if 'q' not in request.GET %}
            <h3 class="heading display-3" style="margin-bottom: 2rem;"> {{ len }} products found in category
                '{{ category }}'</h3>
        {% else %}
            <h4 class="heading display-3" style="margin-bottom: 2rem;"> {{ len }} products found matching your
                search</h4>
        {% endif %}
        <div style="display: flex;flex-wrap:wrap; flex-direction: row">
            <form class="d-flex" method="get" action="{% url 'search in category' category %}"
                  style="width:30%; margin-left: 30%; margin-bottom: 3rem; margin-top:2rem;">
                <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            {% if 'q' in request.GET %}
                <form method="get" action="{% url 'search in category' category %}">
                <input type="hidden" name="q" value="{{ query }}">

            {% else %}
                <form method="get" action="{% url 'category_view' category %}">
            {% endif %}
            {{ sort_form }}
            <button>Filter</button>
            </form>
        </div>

        <div class="parent">
            {% for product in page_obj %}
                <div class="card child">
                    <a href="{% url 'product' product.pk  product.product_name %}">
                        {% with product.productpicture_set.all|first as image %}
                            <img src="{{ image.images.url }}" class="card-img-top" alt="{{ product.product_name }}"
                                 style="height: 300px">
                        {% endwith %}
                    </a>
                    <div class="card-body">
                        <a href="{% url 'product' product.pk product.product_name %}">
                            <h5 class="card-title">{{ product.product_name }}</h5>
                        </a>
                        <h6 class="card-title">{{ product.price }}lv</h6>
                        {#                        <p class="card-text">{{ product.description }}.</p>#}
                        {% include 'partials/add_to_cart.html' %}

                    </div>
                </div>
            {% endfor %}

        </div>
    {% else %}
        <h1 class="heading display-1">No products found</h1>
    {% endif %}
    <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1{% if 'q' in request.GET %}&q={{ query }}{% endif %}&order={{ order }}">First</a>
                            <a href="?page={{ page_obj.previous_page_number }}{% if 'q' in request.GET %}&q={{ query }}{% endif %}&order={{ order }}">
                                Previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} or {{ page_obj.paginator.num_pages }}
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}{% if 'q' in request.GET %}&q={{ query }}{% endif %}&order={{ order }}">Next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}{% if 'q' in request.GET %}&q={{ query }}{% endif %}&order={{ order }}">Last</a>
                        {% endif %}
                    </span>
    </div>
{% endblock %}

website/templates/change_pfp.html
{% extends 'shared/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    <div style="margin-left: 40%">
    <p>Current profile picture</p>
    <img src="{{ pfp.profile_picture.url }}" alt="{{ pfp }}" height="280" width="280" style="border-radius: 50%">
    <form method="post" action="{% url 'change pfp' user.username user.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" style="margin-top:1.2rem;">Change</button>
    </form>
    </div>
{% endblock %}

website/templates/checkout.html
{% extends 'shared/base.html' %}
{% load static %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="checkout-form">
    <form method="post" action="{% url 'order' user.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-warning order-btn">Order</button>
    </form>
    </div>
{% endblock %}

website/templates/create_product.html
{% extends 'shared/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
    {% block product_styles %} <link rel="stylesheet" href="{% static 'css/products.css' %}"> {% endblock %}

{% block content %}
<h1>Add new product</h1>
    <div class="create-product">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    {{ form|crispy }}

    {{ formset.management_form|crispy }}
    {% for form in formset %}
        <p>{{ form }}</p>
    {% endfor %}
        <div class="add-item">
        <button type="submit" class="btn btn-success">Add item</button>
            </div>
    </form>
    </div>
{% endblock %}

website/templates/edit_product.html
{% extends 'shared/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/products.css' %}"> {% endblock %}

{% block content %}
    {% if product.owner_id != id %}
        <h1 style="text-align: center; color:red;">Access denied</h1>
    {% else %}
        <h1>Edit product</h1>
        <div class="create-product">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ formset.management_form|crispy }}
                {% for form in formset %}
                    <p>{{ form }}</p>
                {% endfor %}
                <div class="add-item">
                    <button type="submit" name="profile" value="{{ user.pk }}" class="btn btn-success">Edit item
                    </button>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

website/templates/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
{% endblock %}
{% block content %}
    <form method="get">
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <div class="new-item ">
            <a href="{% url 'create' %}" class="btn btn-primary add">Add new product</a>
        </div>
</form>
        <div class="sort-by">
            <form method="get" action="{% url 'index' %}">
                <input type="hidden" name="page" value="{{ page_obj.number }}">
                {{ sort_form }}
                <button>Filter</button>
            </form>
        </div>
    <div class="container">

{% for product in page_obj %}
{% include 'partials/products.html' %}
{% endfor %}

    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if order %}&order={{ order }}{% endif %}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&order={{ order }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if order %}&order={{ order }}{% endif %}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&order={{ order }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}

website/templates/order_complete.html
{% extends 'shared/base.html' %}
{% load static %}
{% block product_styles %}
    <link rel="stylesheet" href="{% static 'css/order_complete.css' %}">
{% endblock %}
{% block content %}
    <h3 class="order">Your order is complete.</h3>
    <h4 class="order">Total paid: {{ cost }}lv</h4>
    <div class="container">
        {% for product in products %}
            <div class="item" style="margin-bottom:1rem;">
                <img src="{{ product.image_url }}">
                <p>{{ product.product_name }}</p>
                <p>{{ product.price }}lv</p>
            </div>
        {% endfor %}
    </div>
    <div class="center">
        <a class='btn btn-warning' href="{% url 'index' %}">Go back shopping</a>
    </div>
{% endblock %}

website/templates/product.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <img src="{{ product.image_url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ product.product_name }}</h5>
            <h6 class="card-title">{{ product.price }}lv</h6>
            <p class="card-text">{{ product.description }}.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
{% endblock %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ product.image_url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex">
                <h5><u>Product:</u> {{ product.product_name }}</h5>
            </div>
            <div class="d-flex">
                <h5><u>Price:</u> {{ product.price }}</h5>

            </div>
            <p class="mt-2">Description: {{ product.description }}</p>
            <div>
                {% include 'partials/add_to_cart.html' %}
            </div>
            <br>
            {% if user.is_staff or user.pk == product.owner_id %}
            <form method="get" action="{% url 'delete item' product.pk %}">
                {% csrf_token %}
                <button class="btn btn-danger div-item delete-btn" name="delete" value="{{ user.pk }}">Delete product</button>
            </form>
            {% endif %}
            <a href=""><i class="fa fa-heart-o" aria-hidden="true"></i></a>
        </div>
    </div>

website/templates/single_product.html
{% extends 'shared/base.html' %}
{% load crispy_forms_tags %}
{% block product_styles %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% endblock %}
{% block content %}

    <div class="d-flex" style="height:100%">
        <div class="d-inline p-3" style="width:60%; max-height: 50%">
        <div class="w3-content w3-display-container">
            {% with product.productpicture_set.all as images %}
                {% for image in images %}
            <img src="{{ image.images.url }}"
                 class="mySlides" style="margin-left:1in;margin-right:1in; max-width: 80%; max-height: 80%; height: 10cm; width: 12cm;">
                {% endfor %}
                    {% endwith %}
          <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
            <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
        </div>

        </div>
        <div class="d-inline p-2" style="width:35%">
            <div class="d-flex">
                <h5><u>Product:</u> {{ product.product_name }}</h5>
            </div>
            <div class="d-flex">
                <h5><u>Price:</u> {{ product.price }}</h5>

            </div>
            <p class="mt-2 d-flex" style=" height:65%;overflow: hidden;text-overflow:ellipsis; ">
                Description: {{ product.description }}</p>
            <div>
                {% include 'partials/add_to_cart.html' %}
            </div>
            <br>
            {% if user.is_staff or user.pk == product.owner_id %}
                <div class="d-flex">
                    <div class="d-block">
                        <form method="get" action="{% url 'edit_item' product.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-primary div-item">Edit Product</button>
                        </form>
                    </div>
                    <div class="d-block">

                        <form method="get" action="{% url 'delete item' product.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-danger div-item delete-btn"
                                    name="delete" value="{{ user.pk }}" style="margin-left:1rem;">Delete
                                product
                            </button>
                        </form>
                    </div>
                </div>
            {% endif %}
            <pmo>Product viewed : {{ product.views }} times</pmo>
            <a href=""><i class="fa fa-heart-o" aria-hidden="true"></i></a>
        </div>
        <div class="d-inline w-30">
            <h3>Listed by</h3>
            <h4>
                <a href="{% url 'profile' owner.username %}" style="text-decoration: none">{{ owner.username }}</a>
            </h4>

        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3;margin-top:3rem; padding:2%;">
        {% for comment in product_comments %}
            <h5>{{ comment.user }}:</h5>
            <e>{{ comment.text }}</e>
            <hr>
        {% endfor %}
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'product' product.pk product.product_name %}">
                {% csrf_token %}
                {{ comment_form }}
                <button>Submit</button>
            </form>
        {% endif %}
    </div>

    <script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}
</script>
{% endblock %}